## Hooks

# add line numbers
hook global WinCreate .* %{addhl number_lines}

# add brackets highlighting
hook global WinCreate .* %{addhl show_matching}

# soft tabs
hook -group TabExpander global InsertChar \t %{ exec -draft h@}

# scrolloff
set global scrolloff 12,12

# format text with pandoc
map global user g %{ | pandoc --from=markdown --to=markdown --columns=80 <ret> }

# colors
colorscheme default

# custom commands
map global user h XypjXHr=A<ret><ret><esc>
map global user s XypjXHr-A<ret><ret><esc>
map global user b %{ | pandoc-citeproc --bib2yaml --format=biblatex <ret> }

%sh{

localconfdir="$XDG_CONFIG_HOME/kak"

for highlighter in "$localconfdir"/hl/*; do
    cat "$highlighter"
done

}
