#!/usr/bin/zsh

# General Environment
# -------------------

### Directories
export DOTFILES="$HOME/dotfiles"
export DOWNLOADS="$HOME/dl"
export MEDIA="$HOME/media"
export MOVIES="$MEDIA/movies"
export MUSIC="$MEDIA/music"
export SERIES="$MEDIA/series"

### Applications
export VISUAL="/usr/bin/vim"
export EDITOR="/usr/bin/vim"
export VIEWER="jfbview"
export PLAYER="mpv"

### Printing
export PRINT_SERVER="ews"
export PRINTER="siebl-0403-bwd1"

### Path
export PATH="$PATH:/sbin"
export PATH="$PATH:/usr/sbin"
export PATH="$PATH:$HOME/bin"

### Settings
export LANG="en_US.UTF-8"
export GPG_TTY=`tty`

### Colors
echo -en "\e]P4264bc2" # S_blue
echo -en "\e]PC4374a6" # ls blue (default vim blue)

# Specific Environments
# ---------------------

### Markdown
export MD_DATA="$DOTFILES/md"

### Python
export PYTHONPATH="$PYTHONPATH:$HOME/qgl"

### Maude
maude_home="$HOME/src/maude"
maude_main="$maude_home/src/Main"
full_maude="$maude_home/full-maude"
maude_formal_environment="$maude_home/MFE/src"
export MAUDE_LIB="$maude_main:$full_maude:$maude_formal_environment"

# XDG dirs
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$DOTFILES"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DOWNLOAD_DIR="$DOWNLOADS"

# gitnet!
export gn_dir="$HOME/src/gn"

# Load Aliases
# ------------

[[ -f ~/.aliases ]] && source ~/.aliases
