# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

setopt appendhistory extendedglob hist_ignore_all_dups complete_aliases

# Behavior
# --------
setopt appendhistory autocd extendedglob nomatch hist_ignore_all_dups hist_ignore_space
unsetopt beep notify
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall

zstyle :compinstall filename '/home/alli/.zshrc'

autoload -U colors && colors

autoload -Uz compinit promptinit
compinit
promptinit
# End of lines added by compinstall

PROMPT="%F{blue}[%M]%f %F{magenta}%~%f %E"

zsh_dir="$HOME/dotfiles/zsh"
env_files=("profile" "aliases")
for env_file in $env_files; do
    [[ -f "$zsh_dir/$env_file" ]] && source "$zsh_dir/$env_file"
done

